---
# This repo can execute/build under different compute environments
# e.g. AWS, or a local server etc
# This file contains configuration information regarding the
# different environments: e.g. names of services to use
AWS:
  # Docker wrapper extension
  docker_registry_prefix: ECR-REGISTRY.amazonaws.com/myprefix-
  docker_login_command: "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ECR-REGISTRY.amazonaws.com"
  other-option: s3

# The below are placeholders for the actual values
local:
  docker-registry-prefix: ""
  docker_login_command: "echo no login required"
  other-option: s3
