name: CLI Test

on: [pull_request, workflow_dispatch]

jobs:
  cli-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.1.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make install
      - name: Build docker images
        run: |
          source venv/bin/activate \
          && ./repo-cli.py docker build ubuntu_base \
          && ./repo-cli.py docker build ubuntu_derived
      - name: Run command
        run: |
          source venv/bin/activate \
          && ./repo-cli.py docker ubuntu_base "echo 'Hello, World!'"
